//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppEnum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Enrollments = new HashSet<Enrollments>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
        public string Tags { get; set; }
        public int TotalStudentsEnrolled { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int TotalLecturesCount { get; set; }
        public string SubTitle { get; set; }
        public string CourseSummary { get; set; }
        public string CourseShortDescription { get; set; }
        public string Language { get; set; }
        public string Achieve { get; set; }
        public string Requirements { get; set; }
        public string FullDescription { get; set; }
        public string TeacherId { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollments> Enrollments { get; set; }
    }
}
