//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInstructor
    {
        public int CourseInstructorId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> InstructorId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
