//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreyFabricReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreyFabricReceive()
        {
            this.GreyFabricReceiveDetails = new HashSet<GreyFabricReceiveDetail>();
        }
    
        public long Id { get; set; }
        public string CompId { get; set; }
        public string RefId { get; set; }
        public long PartyId { get; set; }
        public string JobNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreyFabricReceiveDetail> GreyFabricReceiveDetails { get; set; }
    }
}
