//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreyFabricReceiveDetail
    {
        public long Id { get; set; }
        public long GreyFabricReceiveId { get; set; }
        public string ColorRefId { get; set; }
        public string SizeRefId { get; set; }
        public int ItemId { get; set; }
        public decimal StretchLength { get; set; }
        public decimal Quantity { get; set; }
        public int NoOfRolls { get; set; }
        public string Remarks { get; set; }
    
        public virtual GreyFabricReceive GreyFabricReceive { get; set; }
    }
}
