//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeAssignment
    {
        public int OfficeAssignmentId { get; set; }
        public string Assignment { get; set; }
        public string Location { get; set; }
        public int InstructorId { get; set; }
    
        public virtual OfficeAssignment OfficeAssignment1 { get; set; }
        public virtual OfficeAssignment OfficeAssignment2 { get; set; }
    }
}
